# Dependencies
markdown:         
highlighter:      

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            ARC596
tagline:          
description:      
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://
IntuitiveRobotics-AugmentedTechnologies.github.io/ARC596_Embodied-Computation/" # the base hostname & protocol for your site, e.g. http://example.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/IntuitiveRobotics-AugmentedTechnologies/ARC596_Embodied-Computation

plugins:
  - jekyll-feed

collections:
  sessions:
    output: true
